export const user = [
  {
    name: "David Miller",
    email: "dmiller@gmail.com",
    phone: "+971234567890",
    location: "Dubai, AE",
    status: "Active",
  },
  {
    name: "David Miller",
    email: "dmiller@gmail.com",
    phone: "+971234567890",
    location: "Dubai, AE",
    status: "Active",
  },
  {
    name: "David Miller",
    email: "dmiller@gmail.com",
    phone: "+971234567890",
    location: "Dubai, AE",
    status: "Suspended",
  },
  {
    name: "David Miller",
    email: "dmiller@gmail.com",
    phone: "+971234567890",
    location: "Dubai, AE",
    status: "Suspended",
  },
  {
    name: "David Miller",
    email: "dmiller@gmail.com",
    phone: "+971234567890",
    location: "Dubai, AE",
    status: "Suspended",
  },
  {
    name: "David Miller",
    email: "dmiller@gmail.com",
    phone: "+971234567890",
    location: "Dubai, AE",
    status: "Active",
  },
  {
    name: "David Miller",
    email: "dmiller@gmail.com",
    phone: "+971234567890",
    location: "Dubai, AE",
    status: "Active",
  },
];
